### ISSUE TITLE
is this project still maintained?🤔 

### ISSUE THREAD

**Issue by kloczek** [graingert/taskgroup#7]
If yes please add git version tag of the last release.
Also sin=ce last release present on pypi (0.0.0a4) looks like some new changes has been added.
Any plans to make new release? 🤔

**Comment by graingert** [comment]
@kloczek hello! This project is somewhat unmaintained. But shouldn't be too hard to get into a maintained state

**Comment by jorenham** [comment]
> But shouldn't be too hard to get into a maintained state

What would that involve? Can we help with that?

**Comment by graingert** [comment]
I've now released 0.1.0! sorry for the delay
